# Generated by Django 5.2.1 on 2025-09-13 09:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название категории')),
                ('icon', models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Иконка категории')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна?')),
            ],
        ),
        migrations.CreateModel(
            name='Addition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название дополнения')),
                ('description', models.TextField(verbose_name='Описание дополнения')),
                ('cost', models.IntegerField(verbose_name='Стоимость дополнения')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Изображение дополнения')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.category', verbose_name='Категория дополнения')),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название услуги')),
                ('description', models.TextField(verbose_name='Описание услуги')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна?')),
                ('cost', models.IntegerField(verbose_name='Стоимость услуги')),
                ('peoples', models.IntegerField(verbose_name='Количество человек')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Изображение услуги')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.category', verbose_name='Категория услуги')),
            ],
        ),
    ]
