# Generated by Django 5.2.1 on 2025-11-03 15:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='minimal_age',
            field=models.IntegerField(default=0, verbose_name='Возрастное ограничение'),
        ),
        migrations.AlterField(
            model_name='service',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='service.category', verbose_name='Категория услуги'),
        ),
    ]
