# Generated by Django 5.2.1 on 2025-11-07 17:58

from django.db import migrations, models
from django.utils.text import slugify


def generate_url_names(apps, schema_editor):
    """Генерирует уникальные url_name для всех существующих услуг"""
    from django.db import connection
    
    Service = apps.get_model('service', 'Service')
    
    with connection.cursor() as cursor:
        for service in Service.objects.all():
            # Генерируем базовый slug из названия
            base_slug = slugify(service.name)
            if not base_slug:
                base_slug = f'service-{service.id}'
            
            # Проверяем уникальность через SQL и добавляем суффикс если нужно
            url_name = base_slug
            counter = 1
            while True:
                cursor.execute(
                    "SELECT COUNT(*) FROM service_service WHERE url_name = %s",
                    [url_name]
                )
                if cursor.fetchone()[0] == 0:
                    break
                url_name = f'{base_slug}-{counter}'
                counter += 1
            
            # Обновляем через SQL
            cursor.execute(
                "UPDATE service_service SET url_name = %s WHERE id = %s",
                [url_name, service.id]
            )


def reverse_generate_url_names(apps, schema_editor):
    """Обратная функция - ничего не делаем"""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_service_minimal_age_alter_service_category'),
    ]

    operations = [
        # Сначала очищаем частично созданные объекты через SQL
        migrations.RunSQL(
            sql="""
                -- Удаляем все индексы связанные с url_name
                DO $$
                DECLARE
                    r RECORD;
                BEGIN
                    FOR r IN (SELECT indexname FROM pg_indexes WHERE tablename = 'service_service' AND indexname LIKE '%url_name%')
                    LOOP
                        EXECUTE 'DROP INDEX IF EXISTS ' || quote_ident(r.indexname);
                    END LOOP;
                END $$;
                
                -- Удаляем колонку если она существует
                ALTER TABLE service_service DROP COLUMN IF EXISTS url_name CASCADE;
            """,
            reverse_sql=migrations.RunSQL.noop,
        ),
        # Добавляем поле через SQL без автоматического создания индекса
        migrations.RunSQL(
            sql="""
                ALTER TABLE service_service 
                ADD COLUMN url_name VARCHAR(100) NULL;
            """,
            reverse_sql="ALTER TABLE service_service DROP COLUMN IF EXISTS url_name;",
        ),
        # Заполняем url_name для всех существующих записей
        migrations.RunPython(generate_url_names, reverse_generate_url_names),
        # Теперь создаем уникальный индекс и делаем поле обязательным
        migrations.RunSQL(
            sql="""
                -- Делаем поле обязательным
                ALTER TABLE service_service 
                ALTER COLUMN url_name SET NOT NULL;
                
                -- Создаем уникальный индекс
                CREATE UNIQUE INDEX service_service_url_name_key ON service_service (url_name);
            """,
            reverse_sql="""
                DROP INDEX IF EXISTS service_service_url_name_key;
                ALTER TABLE service_service ALTER COLUMN url_name DROP NOT NULL;
            """,
        ),
        # Обновляем состояние модели для Django (без изменения БД, так как поле уже создано через SQL)
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.AddField(
                    model_name='service',
                    name='url_name',
                    field=models.SlugField(help_text='Используется в URL для страницы услуги (например: horror-quest)', max_length=100, unique=True, verbose_name='URL идентификатор'),
                ),
            ],
        ),
        migrations.AlterField(
            model_name='addition',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Изображение дополнения'),
        ),
        migrations.AlterField(
            model_name='category',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Иконка категории'),
        ),
        migrations.AlterField(
            model_name='service',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Изображение услуги'),
        ),
    ]
