# Generated by Django 5.2.1 on 2025-10-17 15:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('information', '0001_initial'),
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BirthdayClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Имя клиента')),
                ('phone', models.CharField(max_length=20, verbose_name='Телефон')),
                ('birthday', models.CharField(max_length=5, verbose_name='День и месяц (ДД.ММ)')),
            ],
        ),
        migrations.CreateModel(
            name='CompletedOrders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=200, verbose_name='Услуга')),
                ('additions_list', models.TextField(blank=True, verbose_name='Дополнения')),
                ('schedule_datetime', models.CharField(max_length=100, verbose_name='Дата и время')),
                ('total_cost', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10)),
                ('name', models.CharField(max_length=120, verbose_name='Имя и Фамилия')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('phone', models.CharField(max_length=20, verbose_name='Номер телефона')),
                ('comment', models.CharField(max_length=200, verbose_name='Комментарий пользователя')),
                ('admin_comment', models.CharField(max_length=150, verbose_name='Комментарий администратора')),
            ],
        ),
        migrations.CreateModel(
            name='CorporateClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Имя и Фамилия / Компания')),
                ('phone', models.CharField(max_length=20, verbose_name='Телефон')),
            ],
            options={
                'verbose_name': 'Корпоративный клиент',
                'verbose_name_plural': 'Корпоративные клиенты',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_cost', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10)),
                ('name', models.CharField(max_length=120, verbose_name='Имя и Фамилия')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('phone', models.CharField(max_length=20, verbose_name='Номер телефона')),
                ('comment', models.CharField(max_length=200, verbose_name='Комментарий пользователя')),
                ('admin_comment', models.CharField(max_length=150, verbose_name='Комментарий администратора')),
                ('additions', models.ManyToManyField(blank=True, to='service.addition', verbose_name='Дополнения')),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='information.schedule', verbose_name='Дата и время')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.service', verbose_name='Услуга')),
            ],
        ),
    ]
