# Generated by Django 5.2.1 on 2025-10-17 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_add_missing_tables'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='birthdayclient',
            options={'verbose_name': 'День рождения', 'verbose_name_plural': 'Дни рождения'},
        ),
        migrations.AlterModelOptions(
            name='completedorders',
            options={'verbose_name': 'Завершенный заказ', 'verbose_name_plural': 'Завершенные заказы'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'Заказ', 'verbose_name_plural': 'Заказы'},
        ),
        migrations.AlterField(
            model_name='order',
            name='admin_comment',
            field=models.CharField(blank=True, default='', max_length=150, verbose_name='Комментарий администратора'),
        ),
    ]
