# Generated by Django 5.2.1 on 2025-11-03 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_alter_birthdayclient_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='corporateclient',
            name='date',
            field=models.CharField(default='test', max_length=20, verbose_name='Дата'),
            preserve_default=False,
        ),
    ]
