# Generated by Django 5.2.1 on 2025-11-12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_corporateclient_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='comment',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Комментарий пользователя'),
        ),
    ]

