# Generated by Django 5.2.1 on 2025-11-12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_make_comment_optional'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создано'),
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Ожидает подтверждения'), ('confirmed', 'Подтверждён'), ('cancelled', 'Отменён')], default='pending', max_length=20, verbose_name='Статус'),
        ),
    ]

