# Generated by Django 5.2.1 on 2025-10-17 15:11

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='images/')),
            ],
            options={
                'verbose_name': 'Акция',
                'verbose_name_plural': 'Акции',
            },
        ),
        migrations.CreateModel(
            name='ScheduleBase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('times', django.contrib.postgres.fields.ArrayField(base_field=models.TimeField(), size=None, verbose_name='Список времени в которое работает услуга')),
                ('days', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=None, verbose_name='Номера дней недель по которым работает услуга(Понедельник - 1, Воскресенье - 7')),
                ('prices', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=None, verbose_name='Цена услуги в определенное время(Первое время - первая цена)')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.service', verbose_name='Услуга')),
            ],
            options={
                'verbose_name': 'Шаблон расписания',
                'verbose_name_plural': 'Шаблоны расписания',
            },
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата')),
                ('time', models.TimeField(verbose_name='Время')),
                ('price', models.IntegerField(verbose_name='Цена')),
                ('schedule_base', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='information.schedulebase', verbose_name='Шаблон расписания')),
            ],
            options={
                'verbose_name': 'Расписание',
                'verbose_name_plural': 'Расписание',
                'ordering': ['date', 'time'],
            },
        ),
    ]
