# Generated by Django 5.2.1 on 2025-10-17 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Доступно ли время?'),
        ),
    ]
