# Generated by Django 5.2.1 on 2025-11-07 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0002_schedule_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='mobile_image',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Изображение для мобильных устройств'),
        ),
        migrations.AlterField(
            model_name='action',
            name='image',
            field=models.ImageField(upload_to='', verbose_name='Изображение для десктопа'),
        ),
    ]
