# Generated by Django 5.2.1 on 2025-11-12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0003_action_mobile_image_alter_action_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='reserved_until',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Зарезервировано до'),
        ),
    ]

