"""

Django settings for quests project.

Generated by 'django-admin startproject' using Django 5.2.1.

For more information on this file, see

https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see

https://docs.djangoproject.com/en/5.2/ref/settings/

"""

from pathlib import Path

import os

from celery.schedules import crontab
from corsheaders.defaults import default_headers

from dotenv import load_dotenv  # Р Т‘Р С•Р В±Р В°Р Р†РЎРЉРЎвЂљР Вµ РЎРЊРЎвЂљРЎС“ РЎРѓРЎвЂљРЎР‚Р С•Р С”РЎС“

def env_bool(name: str, default: bool = False) -> bool:
    value = os.getenv(name)
    if value is None:
        return default
    return value.strip().lower() in {"1", "true", "yes", "on"}


def env_list(name: str, default: str = "") -> list[str]:
    raw = os.getenv(name)
    if raw is None:
        raw = default
    return [item.strip() for item in raw.split(",") if item.strip()]


# Build paths inside the project like this: BASE_DIR / 'subdir'.

BASE_DIR = Path(__file__).resolve().parent.parent

# Р вЂ”Р В°Р С–РЎР‚РЎС“Р В·Р С‘РЎвЂљР Вµ Р С—Р ВµРЎР‚Р ВµР СР ВµР Р…Р Р…РЎвЂ№Р Вµ Р С‘Р В· .env РЎвЂћР В°Р в„–Р В»Р В°

load_dotenv(os.path.join(BASE_DIR, '.env'))  # Р Т‘Р С•Р В±Р В°Р Р†РЎРЉРЎвЂљР Вµ РЎРЊРЎвЂљРЎС“ РЎРѓРЎвЂљРЎР‚Р С•Р С”РЎС“

# Quick-start development settings - unsuitable for production

# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!

SECRET_KEY = os.getenv(
    "DJANGO_SECRET_KEY", "django-insecure-d*u@g0dos0%^s(*41fieor84cp9w!6f4g)3i-^+w40dk4bd9-b"
)

# SECURITY WARNING: don't run with debug turned on in production!

DEBUG = env_bool("DJANGO_DEBUG", True)

ALLOWED_HOSTS = env_list("DJANGO_ALLOWED_HOSTS")

# Application definition

REST_FRAMEWORK = {

    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',

    'DATE_FORMAT': '%d.%m.%Y',

}

INSTALLED_APPS = [

    'django.contrib.admin',

    'django.contrib.auth',

    'django.contrib.contenttypes',

    'django.contrib.sessions',

    'django.contrib.messages',

    'django.contrib.staticfiles',

    'corsheaders',

    'rest_framework',

    'drf_spectacular',

    'service',

    'quests',

    'order',

    'information',

    'contacts'

]

MIDDLEWARE = [

    'django.middleware.security.SecurityMiddleware',

    'whitenoise.middleware.WhiteNoiseMiddleware',

    'corsheaders.middleware.CorsMiddleware',

    'django.contrib.sessions.middleware.SessionMiddleware',

    'django.middleware.common.CommonMiddleware',

    'django.middleware.csrf.CsrfViewMiddleware',

    'django.contrib.auth.middleware.AuthenticationMiddleware',

    'django.contrib.messages.middleware.MessageMiddleware',

    'django.middleware.clickjacking.XFrameOptionsMiddleware',

]

ROOT_URLCONF = 'quests.urls'

TEMPLATES = [

    {

        'BACKEND': 'django.template.backends.django.DjangoTemplates',

        'DIRS': [BASE_DIR / "templates"],

        'APP_DIRS': True,

        'OPTIONS': {

            'context_processors': [

                'django.template.context_processors.request',

                'django.contrib.auth.context_processors.auth',

                'django.contrib.messages.context_processors.messages',

            ],

        },

    },

]

WSGI_APPLICATION = 'quests.wsgi.application'

# Database

# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {

    'default': {

        'ENGINE': 'django.db.backends.postgresql',

        'NAME': os.getenv('POSTGRES_DB'),

        'USER': os.getenv('POSTGRES_USER'),

        'PASSWORD': os.getenv('POSTGRES_PASSWORD'),

        'HOST': os.getenv('POSTGRES_HOST'),

        'PORT': os.getenv('POSTGRES_PORT'),

    }

}

# Password validation

# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [

    {

        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',

    },

    {

        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',

    },

    {

        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',

    },

    {

        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',

    },

]

# Internationalization

# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'ru'

TIME_ZONE = 'Europe/Moscow'

USE_I18N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)

# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = os.getenv("DJANGO_STATIC_URL", '/static/')

STATICFILES_DIRS = [

    os.path.join(BASE_DIR, 'static'),  # Р ВµРЎРѓР В»Р С‘ Р С‘РЎРѓР С—Р С•Р В»РЎРЉР В·РЎС“Р ВµРЎвЂљР Вµ Р С•Р В±РЎвЂ°РЎС“РЎР‹ Р С—Р В°Р С—Р С”РЎС“ static

]

STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# Default primary key field type

# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

SPECTACULAR_SETTINGS = {

    'TITLE': 'Quests API',

    'SERVE_INCLUDE_SCHEMA': False,

}

MEDIA_URL = os.getenv("DJANGO_MEDIA_URL", '/images/')

MEDIA_ROOT = os.path.join(BASE_DIR, 'images')

# CORS settings

CORS_ALLOWED_ORIGINS = env_list(
    "CORS_ALLOWED_ORIGINS",
    "http://localhost:3000,http://127.0.0.1:3000,http://localhost:3001,http://127.0.0.1:3001",
)

CORS_ALLOW_CREDENTIALS = env_bool("CORS_ALLOW_CREDENTIALS", True)

CORS_ALLOW_ALL_ORIGINS = env_bool(
    "CORS_ALLOW_ALL_ORIGINS", DEBUG
)  # Р Р°Р·СЂРµС€РёС‚СЊ РІСЃРµ РёСЃС‚РѕС‡РЅРёРєРё РІ СЂРµР¶РёРјРµ СЂР°Р·СЂР°Р±РѕС‚РєРё
CORS_ALLOW_HEADERS = list(default_headers) + ['X-Client-IP']


CSRF_TRUSTED_ORIGINS = env_list(
    "CSRF_TRUSTED_ORIGINS",
    "http://localhost:8000,http://127.0.0.1:8000",
)

USE_X_FORWARDED_HOST = True

ORDER_RATE_LIMIT_MAX_ATTEMPTS = int(os.getenv("ORDER_RATE_LIMIT_MAX_ATTEMPTS", 3))
ORDER_RATE_LIMIT_WINDOW_MINUTES = int(os.getenv("ORDER_RATE_LIMIT_WINDOW_MINUTES", 15))

AUTO_SCHEDULE_ENABLED = env_bool("AUTO_SCHEDULE_ENABLED", True)

AUTO_SCHEDULE_CRON = {

    "day_of_week": os.getenv("AUTO_SCHEDULE_DAY_OF_WEEK", "sun"),

    "hour": int(os.getenv("AUTO_SCHEDULE_HOUR", 4)),

    "minute": int(os.getenv("AUTO_SCHEDULE_MINUTE", 0)),

}

AUTO_SCHEDULE_WEEKS_AHEAD = int(os.getenv("AUTO_SCHEDULE_WEEKS_AHEAD", 2))

AUTO_SCHEDULE_CLEANUP_ENABLED = env_bool("AUTO_SCHEDULE_CLEANUP_ENABLED", True)

AUTO_SCHEDULE_CLEANUP_CRON = {

    "day_of_week": os.getenv("AUTO_SCHEDULE_CLEANUP_DAY_OF_WEEK", "*"),

    "hour": int(os.getenv("AUTO_SCHEDULE_CLEANUP_HOUR", 3)),

    "minute": int(os.getenv("AUTO_SCHEDULE_CLEANUP_MINUTE", 0)),

}

AUTO_SCHEDULE_KEEP_DAYS = int(os.getenv("AUTO_SCHEDULE_KEEP_DAYS", 0))

CELERY_BROKER_URL = os.getenv("CELERY_BROKER_URL", "redis://localhost:6379/0")

CELERY_RESULT_BACKEND = os.getenv("CELERY_RESULT_BACKEND", CELERY_BROKER_URL)

CELERY_TIMEZONE = TIME_ZONE

CELERY_TASK_DEFAULT_QUEUE = os.getenv("CELERY_DEFAULT_QUEUE", "default")

CELERY_TASK_TRACK_STARTED = True

CELERY_TASK_TIME_LIMIT = int(os.getenv("CELERY_TASK_TIME_LIMIT", 60 * 30))  # 30 РјРёРЅСѓС‚ РїРѕ СѓРјРѕР»С‡Р°РЅРёСЋ

CELERY_BEAT_SCHEDULE = {}

if AUTO_SCHEDULE_ENABLED:

    CELERY_BEAT_SCHEDULE["auto-generate-schedule"] = {

        "task": "information.tasks.generate_future_schedule",

        "schedule": crontab(**AUTO_SCHEDULE_CRON),

        "options": {"expires": 60 * 60},

    }

if AUTO_SCHEDULE_CLEANUP_ENABLED:

    CELERY_BEAT_SCHEDULE["cleanup-old-schedule"] = {

        "task": "information.tasks.cleanup_old_schedule",

        "schedule": crontab(**AUTO_SCHEDULE_CLEANUP_CRON),

        "options": {"expires": 60 * 60},

    }







